CODE_OF_CONDUCT.md, CONTRIBUTING.md, ISSUE_TEMPLATE.md, LICENSE, PULL_REQUEST_TEMPLATE.md, TAP.md
Adicionando a primeira versão do TAP
=> Inserindo termo de abertura de projeto

Makefile, README.md
Adicionando o comando de testes no Makefile e no README
Adicionando o comando de testes no Makefile e no README.
Por favor validem a ortografia do README.
[TS09 - Elaborar Docker para ambiente de Desenvolvimento.](https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/24)
Para o time de desenvolvimento rodar os testes automatizados
Rodei os testes e deu OK, já que não tem testes implementados
=> Inserting test command to Makefile and README documentation

codeclimate.yml
Criação e configuração inicial do code climate, adicionando o que deve ser considerado e caminhos que não deverão ser verificados
Issue #39 
Com esta configuração será possível colher novas métricas que auxiliarão a equipe de gestão e de desenvolvimento durante o progresso do projeto.
Verificação pelo site do code climate que foi configurado para observar o repositório do projeto.
=> Configuração inicial do code climate

docs/VISION_DOCUMENT.md
Adding new product features in topic 5
Co-authored-by: joberth rogers <joberth.rogers18@gmail.com>
Co-authored-by: Guilherme Guy <guilhermeguy349@gmail.com>
Foi adicionado novo recurso do produto ao tópico 5 do Documento de Visão.
#41 
Esta refatoração foi necessária após um melhor definição do escopo do projeto, para adicionar nova funcionalidade que o produto deverá conter.
=> Adição de recurso do produto ao Documento de Visão

docs/documentacao_Scrum_Dr_Down.md
Remove the summary
Add the process for estimate the effort of each story
Foi removido o índice do documento, conforme sugestão anterior do @VictorArnaud 
Foi adicionada a descrição do procedimento para a pontuação das histórias, conforme pedido pela @marimendes 
[TS33- Tornar transparente o Scrum utilizado pelo time](https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/18)
Resolve os pedidos de alterações feitos anteriormente
Como se trata de alteração de documento, não houveram testes.
=> Melhoria da documentação do Scrum

docs/EAP.md
Add the second version of EAP
Co-authored-by: João Pedro Sconetto <sconetto.joao@gmail.com>
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/54
=> Adding the EAP

docs/sprints/00/planning.md, docs/sprints/00/results.md, docs/sprints/01/planning.md, docs/sprints/01/results.md
Refatoração dos documentos da sprint 00 e 01
Refatoração dos documentos da sprint 00 e 01
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/47
As sprints 00 e 01 estavam sem os rastreamentos e precisavam ser refatoradas
=> TS29 - Refatorar a documentação da sprint 00 e 01

docs/ADDITIONAL_SPECIFICATION.md
Versão inicial da especificação suplementar, que documenta, basicamente, os requisitos não-funcionais.
Issue #13
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/13
=> TS26 - Criação da especificação suplementar

docs/ARCHITECTURE_DOCUMENT.md
Co-authored-by: Geovana Ramos <geovannna.1998@gmail.com>
Co-authored-by: Elias Bernardo <ebmm01@gmail.com>
Co-authored-by: Guilherme Guy <guilhermeguy349@gmail.com>
Co-authored-by: Gabriela Medeiros <gabriela.medeiros2010@hotmail.com.br>
Co-authored-by: joberth rogers <joberth.rogers18@gmail.com>
Elaboração do Documento de Arquitetura
#12
=> Making architecture document

.editorconfig, docs/sprints/03/planning.md, docs/sprints/03/results.md
Documentação do planejamento e dos resultados da Sprint 3.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/58
Ajuda a resolver a falta de transparência do Scrum utilizado pela equipe do Dr. Down.
Não foi necessário testes
=> Documentação da Sprint 3

docs/ARCHITECTURE_DOCUMENT.md
=> Adição do diagrama de microserviços

.coveragerc, .travis.yml, requirements/local.txt
Adiciona o envio do relatório de cobertura para o code climate.
Issue #79 
Para manter a cobertura de código acima de 90% foi configurado essa ferramenta para que a informação fica de fácil acesso a qualquer membro do projeto e para auditores externos.
Foi testado localmente e foi testado a integração com o Travis CI
=> Support/Code Climate Coverage

docs/mds/ARCHITECTURE_DOCUMENT.md
Inserindo arquitetura de microserviço no documento de arquitetura
Dentro do documento foi detalhado cada etapa da arquitetura e como elas se comunicam entre si.
Por enquanto não há
Modificações solicitadas pela carla
Não foi testado
=> Arquitetura de microserviços

docs/eps/QUALITY_MANAGEMENT_PLAN.md, mkdocs.yml
Documento de planejamento da qualidade do projeto.
#78 
Melhorar o monitoramento e rastreabilidade da qualidade.
=> TS45 quality document

docs/mds/PROTOTIPO_BAIXA_FIDELIDADE.md
Co-authored-by: Gabriela Medeiros <gabriela.medeiros2010@hotmail.com.br>
Co-authored-by: joberth rogers joberth.rogers18@gmail.com
Elaboração do protótipo de baixa fidelidade
#66 
Esse documento tem como propósito descrever as possíveis telas do sites Dr. Down de forma básica.
=> TS36 - low fidelity prototype

.coveragerc
Configuring the coverage to omit __init__.py files
Configura o coverage.py para omitir arquivos __init__.py do teste de cobertura
Não se aplica.
Queda no teste de cobertura com arquivos que não são necessários estarem cobertos por teste
Foi testado com o code climate e com o report do coverage
=> Add a python file for the coverage omit

docs/eps/RISKS.md
Add the risks for each sprint
Add the scale to be used for score the risks
Este documento descreve os riscos do projeto por sprint, assim como a pontuação utilizada para avaliá-los.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/81
Ajuda a tornar transparente e a gerenciar os riscos deste projeto.
Não foram necessários testes.
=> Documentação dos riscos do projeto

drdown/users/models/model_doctor.py, drdown/utils/validators.py
Esse hot fix corrige o erro presente na develop em relação à validação do CRM.
O número do CRM só será aceito com 7 dígitos de números inteiros.
=> Fixing errors on CRM validator

docs/sprints/04/planning.md, docs/sprints/04/results.md, mkdocs.yml
Documentação do planejamento e resultados da Sprint 4 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/104
Ajuda a resolver o problema de manter o processo Scrum utilizado no projeto transparente
=> Documentação da Sprint 4

docs/eps/CANVAS.md, mkdocs.yml
Add the canvas product on eps folder
Add the canvas product on mkdocs page
#89
=> Adding the canvas product

drdown/templates/pages/info.html
A cor da estrela não estava da mesma cor do fundo.
#120
=> Fixing star color in Down's Syndrome Page

docs/eps/ROADMAP.md, docs/eps/ROADMAP_ROLES.md, mkdocs.yml
Add the roadmap roles
Add the roadmap roles on mkdocs
Fixing portugues errors on roadmap
#85
=> Adding the roadmap roles

docs/eps/RISKS.md
O documento dos riscos do projeto foi melhorado com correção de informações e adição de dados da Sprint 5
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/122
Essa atualização busca melhorar o acompanhamento dos riscos deste projeto.
=> Melhoria da documentação dos riscos

docs/eps/CANVAS.md
Fix some epics on epic table
#128
=> BUGFIX - Fixing some issues on canvas

Makefile
Correção de alguns bugs descobertos pela equipe de desenvolvimento no makefile.
Remove erros de dependência cíclica de comandos.
Remove necessidade de rodar o comando make com sudo em coverage-html.
Remove erro de container não encontrado quando make coverage é rodado em certas circunstâncias.
Alguns erros foram descobertos no makefile pelo uso da equipe de desenvolvimento. Após a comunicação dos erros (que dependiam da forma como o makefile era utilizado), eles foram corrigidos.
Os comandos foram testados à mão, em situações que simulam as condições necessárias para os erros acontecerem. Essas situações foram levantados pela equipe de desenvolvimento.
=> Correção de bugs no makefile

docs/eps/EAP.md
=> TS63 refactoring eap

docs/mds/VISION_DOCUMENT.md
Basicamente, a palavra "médico" foi trocada por "equipe de saúde"
#130 
Alteração requerida pelo cliente
=> Switching doctor to health team in vision document

mkdocs.yml
Adiciona os documentos no mkdocs page que estão faltando.
=> Adding docs on mkdocs.yml

docs/index.md
Edit the home page of mkdocs
#149
=> Editing the home page

production-deploy.sh, staging-deploy.sh
Fix staging deploy error
Corrigindo algumas inconsistências do deploy contínuo em homologação
A máquina de deploy não estava executando os comandos de acordo com o esperado
Foi testado no terminal local e no terminal do host
=> Fix script errors

docs/sprints/06/planning.md, docs/sprints/06/results.md
Documentação do planejamento e resultados da Sprint 6 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/166
=> Documentação da Sprint 6

docs/eps/REQUIREMENTS_MAP.md, mkdocs.yml
Fix some issues on requirements map
Co-authored-by: João Pedro Sconetto <sconetto.joao@gmail.com>
#173
=> HOTFIX - Mapa de requisitos 

.travis.yml
HOTFIX
Reorganiza o .travis.yml pois todos os passos não estavam sendo executados.
=> #HOTFIX: Reorganizing .travis.yml

docs/mds/ARCHITECTURE_DOCUMENT.md
Novos componentes da sprint 08 e componentes da sprint 07
Componentes
=> Componentes

.travis.yml, production-deploy.sh, staging-deploy.sh
Fixing staging and prod deploy scritps
Moving travis after_succes to after_script due after_success was
not executing
Co-authored-by: Victor Arnaud <victorhad@gmail.com>
Correções de erro de build do travis
=> Fixing docker login error

drdown/users/models/model_user.py, drdown/users/tests/test_model_user.py, requirements/base.txt
Corrigindo erro em que o teste da idade a calculava erroneamente no ultimo dia do mês.
Modificando implementação do calculo da idade para que não exita resultado negativo.
Correção de erro que estava quebrando build
Por meio de teste unitário
=> HOTFIX: Corrigindo um erro em teste que apenas ocorre em datas específicas

.travis.yml, production-deploy.sh, staging-deploy.sh
Skip clean up step
Fixing image name on shell script
Co-authored-by: Mariana Mendes <mare.s.mendes@gmail.com>
Algumas pequenas correções para consertar os problemas do deploy
Não se aplica.
Corrigir problemas com o deploy e alguns passos do travis.
Testado localmente
Não se aplica
=> Correções pequenas de deploy

docs/mds/ARCHITECTURE_DOCUMENT.md
Finalizando os componentes para todas as sprints de acordo com as funcionalidades
Deixar a arquitetura estável para poder trabalhar nas outras frentes.
=> Inserting components: sprint 09 to 12

docs/sprints/07/planning.md, docs/sprints/07/results.md, mkdocs.yml
Documentação do planejamento e resultados da Sprint 6 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/166
=> Documentação da Sprint 07

docs/eps/RISKS.md
Atualização da documentação dos riscos, com os scores das sprints 7 e 8 e a descrição dos novos riscos.
- Foram adicionados os scores totais dos riscos da sprints 7 e 8
- Foram descritos os novos riscos identificados durante a Sprint 7
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/167
É necessário manter transparente e identificados os riscos do projeto
=> Atualização da documentação dos riscos

docs/eps/PIPELINE.md, mkdocs.yml
Adição do documento do registro do pipeline, além das modificações necessárias.
Registrar o pipeline proposto e em uso pela equipe do Dr. Down para o CI/CD da aplicação.
#208 
Ter o registro de como é realizado o pipeline da aplicação, da codificação até a entrega contínua.
Não se aplica.
Não se aplica.
=> Pipeline Doc

Makefile, utility/populate.py
Foi adicionado um if no populate que checa se o comando recebeu parâmetros. Se ele tiver recebido parâmetro, este será a senha de todos os users, caso contrário as senhas serão geradas aleatoriamente para cada usuário, como já havia sido implementado. Comando make: populate-dev
Torna prático o login com os users do populate.
=> Adding password as parameter option

docs/eps/ROADMAP.md
Fixing the roadmap;
Adding the sprints 13, 14 and 15 on roadmap
Co-authored-by: Joao Pedro Sconetto <sconetto.joao@gmail.com>
#222 
Não se aplica.
=> Adding the version 1.0 of the roadmap

docs/sprints/09/planning.md, docs/sprints/09/results.md
Documentação do planejamento e resultados da Sprint 9 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/227
=> Documentação da Sprint 9

mkdocs.yml
Add the sprint 09 planning and results on mkdocs page
Co-authored-by: João Pedro Sconetto <sconetto.joao@gmail.com>
#234 
Faltou adicionar os dados da sprint 9 no mkdocs
Não se aplica.
=> Adding the sprint 09 on mkdocs

config/settings/base.py
Removing sentry api url to stop recieving logs from develop machines
and start recieving only from the homolog and production hosts
Remoção da URL da API do Sentry para que logs não sejam enviados a partir das máquinas que estão desenvolvendo a aplicação, o Senty continuará a funcionar mas será configurado apenas nas máquinas de homologação e de produção.
#261
Pois receber logs de quando a ferramenta está rodando na máquina de desenvolvimento dos membros da equipe está estourando o limite de logs mensais do plano da organização no Sentry
Não se aplica.
Não se aplica.
=> Removing Sentry Configuration

drdown/medicalrecords/locale/pt_BR/LC_MESSAGES/django.po
Fix the translation of Prescription
#262
=> HOTFIX - Fixing the translation

docs/eps/PIPELINE.md
A revisão do Pipeline com o desenho do seu processo
Para melhorar o entendimento do pipeline de integração, deploy e entrega contínua da  ferramenta Dr. Down foi desenhado o processo para que os membros e colaboradores possam ter uma visão melhor de todo o processo.
#250 
Foi solicitado pela colaborada Carla Rocha para um melhor entendimento de todo pipeline.
Não se aplica.
Não se aplica.
=> Processo do Pipeline

docs/sprints/10/planning.md, docs/sprints/11/planning.md, docs/sprints/11/results.md
Documentação do planejamento e resultados da Sprint 11 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/251
=> Documentação da Sprint 11

mkdocs.yml
Add the sprint 11 on mkdocs page
HOTFIX
#275 
Não se aplica
=> Adding the sprint on mkdocs

config/settings/local.py, config/settings/production.py
Revisão dos ambientes e scripts do deploy contínuo
Revisão de todas as máquinas do ambiente de produção e homologação, revisão dos scripts relacionados ao deploy contínuo e configurações relacionadas aos mesmos. 
#271 
Revisão dos ambientes para a próxima entrega do projeto 
Foi testado via máquina de homologação
Não se aplica
=> TS115 - Environment Reviews

drdown/medicalrecords/tests/test_view_curves.py
Hotfix de correção dos testes que estão quebrando a develop
Não se aplica
Consertar os testes
Testes unitários
Não se aplica
=> HOTFIX/Fixing test_curves_form_invalid_create_view

docs/mds/ARCHITECTURE_DOCUMENT.md
Atualizando diagrama com microsserviço
=> Updating architecture diagram

docs/sprints/13/planning.md, docs/sprints/13/results.md, mkdocs.yml
Documentação do planejamento e resultados da Sprint 12 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/296
=> Documentação da Sprint 13

drdown/medicalrecords/tests/test_view_curves.py, drdown/medicalrecords/views/view_curves.py
Correção do bug no caso de tentativa de criação de uma curva com idade já existente.
#304 
Garantir o o perfeito funcionamento da ferramenta.
Testes unitários
Não se aplica
=> Fixing curves error

drdown/users/locale/pt_BR/LC_MESSAGES/django.po, drdown/users/templates/users/user_confirm_delete.html, drdown/users/templates/users/user_detail.html
Correções no perfil de usuário.
#313 
Aparecia o label de paciente no perfil,mesmo no caso de não haver nenhum paciente relacionado ao responsável cadastrado que não tivesse filhos até determinado momento cadastrados também. Foram feitas alterações no texto de deleção de usuário.
Não precisou ser testado.
=> TS-135 correções no perfil

docs/sprints/07/planning.md, docs/sprints/07/results.md, docs/sprints/08/planning.md, docs/sprints/08/results.md, docs/sprints/09/planning.md, docs/sprints/10/planning.md, docs/sprints/11/planning.md, docs/sprints/13/planning.md
Fixing the papers on the sprints planning and results
Co-authored-by: João Pedro Sconetto <sconetto.joao@gmail.com>
#323 
Durante o projeto houve uma rotação dos papeis e infelizmente foi esquecido de mudar isso na documentação.
=> Fixing the papers

drdown/medicalrecords/locale/pt_BR/LC_MESSAGES/django.po, drdown/medicalrecords/templates/medicalrecords/medicalrecord_curves_form.html
Correções feitas conforme descritas na issue abaixo
#307 
Garantir uma padronização do front-end e correto funcionamento da ferramenta
Não foi necessário
=> TS131 - Correção da aba curvas de crescimento

drdown/events/templates/events/events_form.html, drdown/notifications/templates/notifications/patient_notifications.html, drdown/notifications/templates/notifications/responsible_notifications.html
Correções no form de eventos que estava aceitando 0 reais quando tinha a opção de gratuito, notificações como linha de cuidados apareciam para responsáveis que não tinha filhos cadastrados foram corrigidos e mudança de redirecionamento da linha de cuidado do paciente que estava para o perfil foi redirecionada para a própria do paciente em notificações.
#310 
Necessitava essas mudanças no front para harmonizar o site e torna-lo com 0 bugs em todos os sentidos. 
Não foi preciso.
=> TS-134 Correções Eventos

docs/mds/ARCHITECTURE_DOCUMENT.md
Foi inserido gráficos, novos componentes e fechado tudo relacionado a issue abaixo
[TS142](https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/318)
Deixar mais fácil a visualização dos dados e finalizar a documentação
quantidade planejada vs quantidade definida:
Arquitetura Planejada:
Arquitetura Definida:
=> Finalizando documento de arquitetura

drdown/notifications/templates/notifications/employee_notifications.html, drdown/notifications/templates/notifications/health_team_notifications.html, drdown/notifications/templates/notifications/patient_notifications.html, drdown/notifications/templates/notifications/responsible_notifications.html
Co-authored-by: Daniel Maike <danmke@hotmail.com>
Correção de um bug
Não tem
Corrigir o espaçamento das notificações.
Não se aplica
Comportamento antes da correção:
Comportamento após a correção:
=> Correcting card spacing in notifications

docs/sprints/14/planning.md, docs/sprints/14/results.md, mkdocs.yml
Documentação do planejamento e resultados da Sprint 14 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/312
=> Documentação da Sprint 14

docs/eps/PIPELINE.md
Updating the pipeline image link to show the right image
Correção da imagem no documento do pipeline
Não se aplica
Correção
Não se aplica
Não se aplica
=> Fixing pipeline image link

docs/POSTMORTEM.md, docs/postmortem.md, mkdocs.yml
=> Adding the postmortem

docs/eps/RISKS.md, docs/sprints/15/planning.md, docs/sprints/15/results.md, mkdocs.yml
Documentação do planejamento e resultados da Sprint 15 do projeto Dr. Down.
https://github.com/fga-gpp-mds/2018.1-Dr-Down/issues/313
=> Documentação da Sprint 15
